layout_spectrum: 0.6771206
typography_spectrum: 0.3835126
color:
  saturation: 0
  brandStrength: 0.7669477
  lightness: 0
  rhythmicContrast: 0
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Russelldallas
